[build]
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions"  # Functions directory
  edge_functions = "netlify/edge_functions"  # Edge Functions directory

[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 301

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"

 [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200